library(knitr)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata) 
library(dplyr)
library(stringr)
library(rvest)
library(readr)
library(tidyr)
library(shiny)
lingData <- read_csv("cleaned_lingData.csv")
unique(lingData$question, na.rm = TRUE)
